server.port=8080

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

dpi.engine.path=C:/Users/gulso/Downloads/dpi-fullstack/engine/Packet_analyzer-main/build/dpi_simple.exe
dpi.engine.timeout=120
dpi.storage.upload=./storage/uploads/
dpi.storage.output=./storage/output/


logging.level.com.dpi=DEBUG
logging.pattern.console=%d{HH:mm:ss} %-5level %logger{20} - %msg%n
